# Uncomment the next line to define a global platform for your project
platform :ios, '10.3'

target 'NoiseRecorder' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NoiseRecorder
  pod 'GCDWebServer', '~> 3.0'
  pod 'GCDWebServer/WebUploader', '~> 3.0'
  pod 'GCDWebServer/WebDAV', '~> 3.0'
end
